#!/usr/bin/env bash
#domain zone so that the subdomain www points to your load-balancer IP
information () {
	local subdomain="$1"
	local domain="$2"
	local record_type="$3"
	local destination="$4"
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}
query_dns() {
	local subdomain="$1"
	local domain="$2"
	dig_result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
	record_type=$(echo "$dig_result" | awk '/IN\s/{print $4}')
	destination=$(echo "$dig_result" | awk '/IN\s/{getline; print $1}')
	information "$subdomain" "$domain" "$record_type" "$destination"
}
main() {
	local domain="$1"
	local subdomain="$2"
	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi
	for sub in "${subdomains[@]}"; do
		query_dns "$sub" "$domain"
	done
}
if [ "$#" -lt 1 ]; then
	echo "Usage: $0 <domain> [subdomain]"
	exit 1
fi
main "$1" "$2"
