#!/usr/bin/env bash
#/redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '/server_name _;/a \\\tlocation /redirect_me {\n\t\t return 301 https://youtube.com;\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx start
