#!/usr/bin/env bash
#/redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '/server_name _;/a location \/redirect_me { return 301 https:\/\/www.youtube.com permanent; }' /etc/nginx/sites-available/default
sudo service nginx start
