#!/usr/bin/env bash
#/redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '37i\rewrite ^/redirect_me https://youtube.com permanent;' /etc/nginx/sites-available/default
sudo service nginx start
