#!/usr/bin/env bash
#custom 404 page that contains the string Ceci n'est pas une page.
apt-get -y update
apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sed -i '/server_name _;/a error_page 404 /404.html;' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '37i/rewrite ^/redirect_me https://youtube.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
