#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
apt-get -y update
apt-get -y install haproxy
echo '  listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 426325-web-01 54.162.75.3:80 check
	server 426325-web-02 100.25.45.16:80 check' | sudo tee /etc/haproxy/haproxy.cfg
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
service haproxy start
