#!/usr/bin/env bash
#manages manage_my_process
if [ $# -eq 0 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
fi
case "$1" in
	start)
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pkill -f "./manage_my_process"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		$0 stop
		sleep 2
		$0 start
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
