#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, 
#displays Best School and then Hi on a new line.
counter=0
while [ $counter -lt 10 ]
do
	if [ $counter -eq  8 ]
	then
		printf "Best School\nHi\n";
	else
		echo "Best School"
	fi
	((counter++))
done
