#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:
#isplays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		printf "bad luck\n";
	elif [ $counter -eq 8 ]
	then
		printf "good luck\n";
	else
		echo "Best School";
	fi
	((counter++))
done
