#!/usr/bin/env bash
#configures an Ubuntu server
cp /etc/hosts ~/hosts.update
echo "127.0.0.2 	localhost" > ~/hosts.update
echo "8.8.8.8  		facebook.com" >> ~/hosts.update
cp -f ~/hosts.update /etc/hosts
