#!/usr/bin/env bash
#configures an Ubuntu server
cp /etc/hosts ~/hosts.update
sed -i s/127.*$/127.0.0.2\\tlocalhost ~/hosts.update
echo "8.8.8.8  		facebook.com" >> ~/hosts.update
cp -f ~/hosts.update /etc/hosts
